 const specializationData = [
  { id: 1, name: "Cardiology" },
  { id: 2, name: "Dermatology" },
  { id: 3, name: "Endocrinology" },
  { id: 4, name: "Gastroenterology" },
  { id: 5, name: "Hematology" },
  { id: 6, name: "Infectious Disease" },
  { id: 7, name: "Internal Medicine" },
  { id: 8, name: "Nephrology" },
  { id: 9, name: "Neurology" },
  { id: 10, name: "Obstetrics and Gynecology" },
  { id: 11, name: "Oncology" },
  { id: 12, name: "Ophthalmology" },
  { id: 13, name: "Orthopedics" },
  { id: 14, name: "Otolaryngology" },
  { id: 15, name: "Pediatrics" },
  { id: 16, name: "Pulmonology" },
  { id: 17, name: "Psychiatry" },
  { id: 18, name: "Radiology" },
  { id: 19, name: "Rheumatology" },
  { id: 20, name: "Surgery" },
  { id: 21, name: "Urology" },
  { id: 22, name: "Family Medicine" },
  { id: 23, name: "Emergency Medicine" },
  { id: 24, name: "Physical Medicine and Rehabilitation" },
  { id: 25, name: "Allergy and Immunology" },
  { id: 26, name: "Geriatrics" },
  { id: 27, name: "Nuclear Medicine" },
  { id: 28, name: "Anesthesiology" },
  { id: 29, name: "Pain Medicine" },
  { id: 30, name: "Sports Medicine" },
];

export default specializationData